{% set name = "package_name" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

requirements:
  host:
    - pip
    - python>=3.10
    - setuptools
    - networkx>=3.10
    - tqdm
    - ag2
  build:
    - python
    - setuptools
  run:
    - numpy
    - python>=3.10
    - networkx>=3.10
    - tqdm
    - ag2

about:
  home: "https://github.com/giuliorossetti/LLM_Network"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Opinion Dynamic simulation with networked LLM agents"
  doc_url: "https://llm_network.readthedocs.io/"
  dev_url: "https://github.com/giuliorossetti/llm_network"

extra:
  recipe-maintainers:
    - GiulioRossetti
